[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/jotacamou/xCAT-go"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"
